# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

init:
  - git config --global core.autocrlf input

branches:
  only:
    - master

# what combinations to test
environment:
  matrix:
    - nodejs_version: 7
      job_part: test
    - nodejs_version: 6
      job_part: test
    - nodejs_version: 4
      job_part: test

install:
  - ps: Install-Product node $env:nodejs_version x64
  - yarn install

build: off

matrix:
  fast_finish: true

test_script:
  - node --version
  - npm --version
  - cmd: yarn run appveyor:%job_part%
